<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSAccount extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('s_account', function (Blueprint $table) {
            $table->bigIncrements('id')->comment('Primary key');
            $table->unsignedBigInteger('m_staff_id')
                ->comment('Fk reference to staff');
            $table->string('firebase_uid', 128)
                ->nullable(true)
                ->comment('firebase UID');
            $table->string('role', 20)
                ->nullable(true)
                ->comment('Role : tenant/admin/user');
            $table->string('username', 25)
                ->nullable(true)
                ->comment('User name');
            $table->string('email', 128)
                ->nullable(true)
                ->comment('E-mail address: Manage your e-mail address in your account as it may be used for login');
            $table->string('password', 128)
                ->nullable(true)
                ->comment('Password: Hashed by SHA256');
            $table->string('pin_code', 4)
                ->nullable(true)
                ->comment('Personal Identification Number');
            $table->string('tmp_passwd', 128)
                ->nullable(true)
                ->comment('Temporary Password: Password automatically generated by the system');
            $table->date('exp_of_tmp_passwd')
                ->nullable(true)
                ->comment('Temporary Password Expiration : Required when setting the primary password');
            $table->string('locale', 2)
                ->default('en')
                ->comment('Locale');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')
                ->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
            $table->softDeletes();
            $table->unsignedBigInteger('modified_by')
                ->nullable(true)
                ->comment('Last Modified By: Saves the s_account.id of the last modified person');
            $table->foreign('m_staff_id')
                ->references('id')
                ->on('m_staff');
            $table->index(['m_staff_id']);
        });
        DB::statement("ALTER TABLE `s_account` comment 'System account master data'");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('s_account');
    }
}
